class VrijOpNaam:
    VRIJOPNAAM_USERNAME = 'VRIJOPNAAM_USERNAME'
    VRIJOPNAAM_PASSWORD = 'VRIJOPNAAM_PASSWORD'
    USERNAME = 'username'
    PASSWORD = 'password'
    CSRF_TOKEN = 'csrfmiddlewaretoken'
    ASK_STAY_SIGNED_IN = 'ask_stay_signed_in'
    STAY_SIGNED_IN_BTN = 'stay_signed_in_btn'
    URL = 'https://vrijopnaam.app'
    PRICING_ELECTRICITY = 'pricing-electricity'
    PRICING_GAS = 'pricing-gas'
    ON = 'on'
    YES = 'yes'
    SESSION_ID = 'sessionid'
    TODAY = 'Vandaag'
    YESTERDAY = 'Gisteren'
    TOMORROW = 'Morgen'
    PRICING_TABS = (PRICING_ELECTRICITY, PRICING_GAS)
